api/urls.py
from django.conf.urls import patterns, include
from tastypie.api import Api

from api.resources import *


v1_api = Api(api_name='v1')

# Taxonomy
v1_api.register(TopicResource())
v1_api.register(ArticleCategoryItemResource())
v1_api.register(TypeOfNeedResource())
v1_api.register(TypeOfSupportResource())
v1_api.register(InterestResource())
v1_api.register(UserRoleResource())
v1_api.register(CountryResource())
v1_api.register(OrganizationTypeResource())
v1_api.register(InvestorTypeResource())
v1_api.register(OrganizationProductLaunchResource())
v1_api.register(OrganizationFundingResource())
v1_api.register(OrganizationGrowthStageResource())

############## New For 2018 ######################
v1_api.register(ProgramTypeResource())
v1_api.register(TypeOfOfficeResource())
v1_api.register(TypeOfFocusSectorResource())
v1_api.register(TypeOfFocusIndustryResource())
v1_api.register(TypeOfStageOfParticipantResource())
v1_api.register(TypeOfInvestmentResource())
v1_api.register(TypeOfInvestmentStageResource())
v1_api.register(TypeOfFundingResource())
v1_api.register(TypeOfBatchResource())
v1_api.register(TypeOfFinancialSourceResource())
v1_api.register(TypeOfAssistantshipResource())
v1_api.register(TypeOfAttachmentResource())
v1_api.register(JobRoleResource())
v1_api.register(LocationResource())

# Account
v1_api.register(UserResource())
v1_api.register(PartyLiteResource())
v1_api.register(PartyResource())

# Organization
v1_api.register(OrganizationResource())
v1_api.register(ProgramResource())
v1_api.register(JobResource())
v1_api.register(UserApplyJobResource())
v1_api.register(OrganizationJobsResource())
v1_api.register(SkillResource())
v1_api.register(JobTagResource())
v1_api.register(OrganizationStaffResource())


# Relation
v1_api.register(OrganizationHasPeopleResource())
v1_api.register(PartySupportPartyResource())
v1_api.register(PartyInvestPartyResource())
v1_api.register(PartyPartnerPartyResource())
v1_api.register(PartyFollowPartyResource())
v1_api.register(PartyContactPartyResource())
v1_api.register(PartyTestifyPartyResource())
v1_api.register(OrganizationParticipateResource())
v1_api.register(PartyInviteTestifyPartyResource())
v1_api.register(PartyReceivedFundingPartyResource())
v1_api.register(PartyReceivedInvestingPartyResource())
v1_api.register(PartyLoveResource())
v1_api.register(UserExperienceOrganizationResource())

# Party
v1_api.register(PortfolioResource())
v1_api.register(PartyFollowingResource())

#CMS
v1_api.register(NewsResource())
v1_api.register(EventResource())
v1_api.register(NewsTagResource())
v1_api.register(EventTagResource())


# Notification
v1_api.register(VerbResource())
v1_api.register(NotificationResource())
v1_api.register(RequestResource())

v1_api.register(HappeningResource())

v1_api.register(SearchResource())

urlpatterns = patterns('',
    (r'', include(v1_api.urls)),
)

asip/urls.py
import os
import autocomplete_light
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse
from django.views.generic import TemplateView

from django.conf.urls.i18n import i18n_patterns

autocomplete_light.autodiscover()
admin.autodiscover()

CUSTOM_ENABLED = True
try:
    import custom.urls
except ImportError:
    CUSTOM_ENABLED = False


# urlpatterns = i18n_patterns('', # not trans now
urlpatterns = patterns('',
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^tagging_autocomplete_tagit/', include('tagging_autocomplete_tagit.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^files-widget/', include('files_widget.urls')),
    url(r'^account/', include('account.urls', app_name='accoount')),
    url(r'^people/', include('account.people_urls', app_name='account')),
    url(r'^organization/', include('organization.urls', app_name='organization')),
    url(r'^people/', include('account.people_urls', app_name='account')),
    url(r'^forum/', include('forum.urls', app_name='forum')),

    url(r'^api/', include('api.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'', include('notification.urls')),
    url(r'', include('taxonomy.urls', app_name='taxonomy')),

    url(r'', include('organization.job_urls', app_name='organization')),
    url(r'', include('party.urls', app_name='party')),
    url(r'', include('relation.urls', app_name='relation')),
    url(r'', include('cms.urls', app_name='cms')),
    url(r'', include('account.connect_urls', app_name='account')),

    url(r'', include('social_auth.urls')),
    url(r'', include('presentation.urls', app_name='presentation')),
    # No swap order url
    url(r'', include('account.role_urls', app_name='account')),
    url(r'', include('special.urls', app_name='special')),
    url(r'', include('organization.role_urls', app_name='organization')),

)

if CUSTOM_ENABLED:
    # urlpatterns += i18n_patterns('', # not trans now
    urlpatterns += patterns('',

        url(r'', include('custom.urls')),
    )

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
        url(r'^404$', TemplateView.as_view(template_name='404.html')),
        url(r'^500$', TemplateView.as_view(template_name='500.html')),
    )

    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

else:
    urlpatterns += patterns('',
        url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    )


handler403 = 'presentation.views.handler403'

custom/urls.py
from django.conf.urls import url, patterns

urlpatterns = ()

'''
urlpatterns = patterns('custom.views',

    url(r'^(?P<organization_role_permalink>[A-Za-z0-9-_.]+)/(?P<organization_role_permalink>[A-Za-z0-9-_.]+)/organization/$', 'organization_role_list', name='organization_role_list'),

    url(r'^(?P<organization_role_permalink>[A-Za-z0-9-_.]+)/(?P<organization_permalink>[A-Za-z0-9-_.]+)/(?P<organization_id>\d+)/$',
        'organization_role_detail', name='organization_role_detail'),
    url(r'^(?P<organization_role_permalink>[A-Za-z0-9-_.]+)/(?P<organization_permalink>[A-Za-z0-9-_.]+)/$',
        'organization_role_detail', name='organization_role_detail_redirect'),

)
'''

organization/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('organization.views',
    url(r'^(?P<organization_id>\d+)/edit/$', 'organization_edit', name='organization_edit'),
    url(r'^(?P<organization_id>\d+)/generate-pdf/(?P<bypass_key>[A-Za-z0-9-_.]+)/$', 'organization_generate_pdf', name='organization_generate_pdf'),
    url(r'^(?P<organization_id>\d+)/pdf/$', 'organization_pdf', name='organization_pdf'),

    url(r'inline/create/$', 'organization_inline_create', name='organization_inline_create'), # TODO: fixed
    url(r'^(?P<type_of_organization>[A-Za-z0-9-_.]+)/create/$', 'organization_create', name='organization_create'),
    #url(r'^(?P<organization_permalink>[A-Za-z0-9-_.]+)/$', 'organization_detail', name='organization_detail'),
    url(r'^(?P<type_of_organization>[A-Za-z0-9-_.]+)/$', 'organization_type_list', name='organization_type_list'),
    url(r'^$', 'organization_list', name='organization_list'),

)

organization/models.py
# -*- coding: utf-8 -*-
import ast
from datetime import timedelta
import inspect
import json
import pickle
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models, IntegrityError
from django.template.defaultfilters import truncatechars
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _, pgettext_lazy
from haystack.inputs import Raw
from haystack.query import SearchQuerySet
from djmoney.models.fields import MoneyField
import tagging

from ckeditor.fields import RichTextField
from common.constants import STATUS_PENDING, STATUS_DRAFT, SUMMARY_MAX_LENGTH, STATUS_PUBLISHED, STATUS_CHOICES, \
    TYPE_SOCIAL_ENTERPRISE, TYPE_STARTUP, TYPE_SUPPORTING_ORGANIZATION, TYPE_INVESTOR, TYPE_PROGRAM, \
    TYPE_CHOICES, EXPAND_TYPE_CHOICES
from common.forms import BetterDecimalField, BetterPositiveIntegerField
from common.functions import instance_get_thumbnail, camelcase_to_underscore, convert_money

from common.models import AbstractPermalink, CommonTrashModel, CommonModel, CachedModel, PriorityModel, StatisitcAccess
from multiselectfield import MultiSelectField
from party.models import Party

import files_widget
from relation.models import BaseRelation
from tagging_autocomplete_tagit.models import TagAutocompleteTagItField
from taxonomy.models import Location, JobRole

USER_MODEL = settings.AUTH_USER_MODEL


def formset_getter(instance, field_name):

    field_name = 'store_%s' % field_name
    value = getattr(instance, field_name) or '[]'
    setattr(instance, field_name, value)

    return ast.literal_eval(value)

def formset_setter(instance, field_name, value):

    field_name = 'store_%s' % field_name
    value = value or []
    setattr(instance, field_name, value)


# Section 1
class AbstractOrganizationSection1(models.Model):

    class Meta:
        abstract = True

    report_start_date = models.DateField(verbose_name=_('Report Start Date'), null=True, blank=True,
        help_text=_('Start date of the reporting period for this IRIS report.')
    )
    report_end_date = models.DateField(verbose_name=_('Report End Date'), null=True, blank=True,
        help_text=_('End date of the reporting period for this IRIS report.')
    )

    # Duplicates
    # name_of_organization = name
    # organization_web_address = homepage_url

    year_founded = models.PositiveSmallIntegerField(verbose_name=_('Year Founded'), null=True, blank=True,
        help_text=_('Year the organization was founded.')
    )
    name_of_representative = models.CharField(verbose_name=_('Name of representative'), null=True, blank=True, max_length=255)

    GENDER_CHOICES = (
        ('M', _('Male')),
        ('F', _('Female')),
        ('N', _('Prefer not to say')),
    )
    gender_of_representative = models.CharField(verbose_name=_('Gender of representative'), null=True, blank=True, max_length=1, choices=GENDER_CHOICES)
    brief_bio_of_representative = RichTextField(verbose_name=_('Brief bio of representative'), null=True, blank=True, config_name='minimal')

    LEGAL_STRUCTURE_CHOICES = (
        ('1', _('Corporation')),
        ('2', _('Limited Liability Company')),
        ('3', _('Non-Profit/Foundation/Association')),
        ('4', _('Partnership')),
        ('5', _('Sole-proprietorship')),
        ('6', _('Cooperative')),
        ('Other', _('Other'))
    )
    legal_structure = models.CharField(verbose_name=_('Legal Structure'), null=True, blank=True, max_length=255, choices=LEGAL_STRUCTURE_CHOICES,
        help_text=_('Current legal structure of the organization.')
    )
    location_of_organizations_headquarters = models.CharField(verbose_name=_("Location of Organization's Headquarters"), null=True, blank=True, max_length=255)
    store_phone_number_of_organizations_headquarters = models.TextField(null=True, blank=True)  # formset
    store_email_of_organizations_headquarters = models.EmailField(
        verbose_name=_('Email of Organization'),
        max_length=255,
        null=True,
        blank=True
    )

    title_of_contact_person = models.TextField(null=True, blank=True)
    email_of_contact_person = models.EmailField(
        verbose_name=_('Email of Contact Person'),
        max_length=255,
        null=True,
        blank=True
    )
    phone_number_of_contact_person = models.TextField(null=True, blank=True)

    store_location_of_organizations_operating_facilities = models.TextField(verbose_name=_("Location of Organization's Operating Facilities"), null=True, blank=True) # formset

    name_of_referring_organization = models.CharField(verbose_name=_("Name of referring organization"), null=True, blank=True, max_length=255)
    contact_information_of_referring_organization = models.CharField(verbose_name=_("Contact information of referring organization"), null=True, blank=True, max_length=255)

    sector_activities = models.ManyToManyField('taxonomy.Topic', verbose_name=_('Sector Activities'),  null=True, blank=True, related_name='sector_activities_topics',
        help_text= _("Primary sectors impacted by the organization's operations.")
    )
    TARGET_BENEFICIARY_CHOICES = (
        ('1', _('Women')),
        ('2', _('Diabilities')),
        ('3', _('Children')),
        ('4', _('Ethnic Minority')),
        ('5', _('Elderly')),
        ('6', _('NEET')),
        ('7', _('Migrant Workers')),
        ('8', _('Youth')),
        ('9', _('LGBT')),
        ('Other', _('Others'))
    )
    target_beneficiary = MultiSelectField(verbose_name=_('Target Beneficiary'), null=True, blank=True, max_length=255, choices=TARGET_BENEFICIARY_CHOICES)

    # Duplicates
    # company_description = description

    mission_statement = RichTextField(verbose_name=_('Mission Statement'), null=True, blank=True,
        help_text=_('Mission statement of the organization.'),
        config_name='minimal'
    )

    @property
    def phone_number_of_organizations_headquarters(self):
        return formset_getter(self, inspect.stack()[0][3])

    @phone_number_of_organizations_headquarters.setter
    def phone_number_of_organizations_headquarters(self, value):
        formset_setter(self, inspect.stack()[0][3], value)

    @property
    def location_of_organizations_operating_facilities(self):
        return formset_getter(self, inspect.stack()[0][3])

    @location_of_organizations_operating_facilities.setter
    def location_of_organizations_operating_facilities(self, value):
        formset_setter(self, inspect.stack()[0][3], value)



# Section 2
class AbstractOrganizationSection2(models.Model):

    class Meta:
        abstract = True

    productservice_type = models.ManyToManyField('taxonomy.Topic', verbose_name=_('Product/Service Type'), null=True, blank=True, related_name='productservice_type_topics',
        help_text=_('Type of product or service provided by the organization')
    )
    productservice_description = RichTextField(verbose_name=_('Product/Service Description'), null=True, blank=True,
        help_text=_('Description of the product or service.'),
        config_name='default'
    )

    # ==============================================================
    definition_of_unit_of_measure_1 = models.CharField(verbose_name=_('Definition of unit of measure 1'), null=True, blank=True, max_length=512)
    unit_of_impact_measurement_1 = models.CharField(verbose_name=_('Unit of Impact Measurement 1'), null=True, blank=True, max_length=512)

    definition_of_unit_of_measure_2 = models.CharField(verbose_name=_('Definition of unit of measure 2'), null=True, blank=True, max_length=512)
    unit_of_impact_measurement_2 = models.CharField(verbose_name=_('Unit of Impact Measurement 2'), null=True, blank=True, max_length=512)

    definition_of_unit_of_measure_3 = models.CharField(verbose_name=_('Definition of unit of measure 3'), null=True, blank=True, max_length=512)
    unit_of_impact_measurement_3 = models.CharField(verbose_name=_('Unit of Impact Measurement 3'), null=True, blank=True, max_length=512)

    store_measurement_year_values = models.TextField(verbose_name=_("Measurement Year and Values"), null=True, blank=True) # formset

    # ==============================================================

    CLIENT_TYPE_CHOICES = (
        ('1', _('Individuals/Households')),
        ('2', _('Microenterprises')),
        ('3', _('Small-to-Medium Enterprises')),
        ('4', _('Large Enterprises')),
        ('5', _('Non-profit / Non-Governmental Organization / Foundations')),
        ('6', _('Government')),
        ('7', _('International Organizations')),
        ('Other', _('Others'))
    )
    client_type = MultiSelectField(verbose_name=_('Client Type'), null=True, blank=True, max_length=255, choices=CLIENT_TYPE_CHOICES,
        help_text=_("Types of entities that are buyers or recipients of the organization's products and/or services")
    )
    client_information = RichTextField(verbose_name=_('Client Information'), null=True, blank=True,
        help_text=_('Name of major clients, if they are business or government'),
        config_name='minimal'
    )

    client_locations = models.ManyToManyField('taxonomy.Country', verbose_name=_('Client Locations'), null=True, blank=True, related_name='client_locations',)
    # Duplicates
    # client_locations = country

    @property
    def measurement_year_values(self):
        result = formset_getter(self, inspect.stack()[0][3])
        result = sorted(result, key=lambda k: k['year_of_datapoint'])
        return result

    @measurement_year_values.setter
    def measurement_year_values(self, value):
        formset_setter(self, inspect.stack()[0][3], value)

# Section 3
class AbstractOrganizationSection3(models.Model):

    class Meta:
        abstract = True

    store_top_3_major_investors_year_and_amount = models.TextField(verbose_name=_('Top 3 major investors, year and amount'), null=True, blank=True)

custom/templates/organization/inline_form.html
{% load i18n %}
{% load organization_tags %}
{% load common_tags %}

{% csrf_token %}

<input type="hidden" name="_win_name" value="{{ win_name }}"/>
<input type="hidden" name="no_script" value="{{ no_script }}"/>
<input type="hidden" name="return_display_name" value="{{ return_display_name }}"/>
<input type="hidden" name="force_type_of_organization" value="{{ force_type_of_organization }}"/>
<input type="hidden" name="required_address" value="{{ required_address }}"/>
<input type="hidden" name="required_contact" value="{{ required_contact }}"/>
<input type="hidden" name="is_mockup" value="{{ is_mockup }}"/>
{{ form.organization_type__permalink }}

<div class="controls form-group{% if force_type_of_organization %} hidden{% endif %}">
    <label for="id_type_of_organization" class="field-container control-label">{% trans "Type of Organization" %}</label>
    <div class="field-container">
        {% for type_of_organization in form.type_of_organization %}
            <div>
                <span class="choice-item">
                    {{ type_of_organization.tag }}
                    <label for="id_type_of_organization_{{ type_of_organization.index }}">{{ type_of_organization.choice_label }}</label>
                </span>
            </div>
        {% endfor %}

        {% if form.type_of_organization.errors %}
        <div class="errors alert alert-danger">{{ form.type_of_organization.errors }}</div>
        {% endif %}
    </div>
</div>

<div class="controls form-group">
    <label for="id_name" class="field-container control-label">{% trans "Name" %} <span class="asterisk text-danger">*</span></label>
    <span class="help-block">
    {% trans "Organization/Product/Service name." %}
    </span>
    <div class="field-container">
        {{ form.name }}
        {% if form.name.errors %}
        <div class="errors alert alert-danger">{{ form.name.errors }}</div>
        {% endif %}
    </div>
</div>

<div class="controls form-group">
    <label for="id_image" class="field-container control-label">{% trans "Image" %}</label>
    <span class="help-block">
    {% trans "Insert organization logo." %}
    </span>
    <div class="field-container">
        {{ form.image }}
        {% if form.image.errors %}
        <div class="errors alert alert-danger">{{ form.image.errors }}</div>
        {% endif %}
    </div>
</div>

<div class="controls form-group{% if not required_address %} hide{% endif %}">
    <label for="id_location_of_organizations_headquarters" class="field-container control-label">{% trans "Office Address" %}</label>
    <div class="field-container">
        {{ form.location_of_organizations_headquarters }}
        {% if form.location_of_organizations_headquarters.errors %}
        <div class="errors alert alert-danger">{{ form.location_of_organizations_headquarters.errors }}</div>
        {% endif %}
    </div>
</div>


<div class="controls form-group{% if not required_contact %} hide{% endif %}">
    <label for="id_store_email_of_organizations_headquarters" class="field-container control-label">{% trans "Organization Email" %}</label>
    <div class="field-container">
        {% if is_mockup %}
        <div class="help-block">
            This email will be sent to invite this organization
        </div>
        {% endif %}
        {{ form.store_email_of_organizations_headquarters }}
        {% if form.store_email_of_organizations_headquarters.errors %}
        <div class="errors alert alert-danger">{{ form.store_email_of_organizations_headquarters.errors }}</div>
        {% endif %}
    </div>
</div>
<div class="controls form-group{% if not required_contact %} hide{% endif %}" id="inline-contact-tel-{{ win_name }}">
    {% render_formset phone_number_of_organizations_headquarters_formset 'phone_number_of_organizations_headquarters' 'Tel/Mobile' %}
</div>

<div class="controls form-group">
    <div class="form-action">
        <button class="btn btn-primary btn-orange" type="submit">{% if form.is_new %}{% trans "Save new" %}{% else %}{% trans "Save changes" %}{% endif %}</button>
        <a href="." class="btn btn-cancel flat-btn">{% trans "Cancel" %}</a>

    </div>
</div>



{% if not form.is_valid %}
{% if not no_script %}
<link type="text/css" href="/static/files_widget/css/widgets.css" media="all" rel="stylesheet" />
<script type="text/javascript" src="/static/libs/jquery-ui/js/jquery-ui-1.10.4.min.js"></script>
{% endif %}
<script type="text/javascript" src="/static/files_widget/js/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="/static/files_widget/js/jquery.fileupload.js"></script>
<script type="text/javascript" src="/static/files_widget/js/widgets.js"></script>
{% endif %}

<script type="text/javascript">

    (function ($) {

        var win = {
            'name': '{{ win_name }}',
            'close': function () {
                //delete(CKEDITOR.instances.id_description);
                $('.field-inline-{{ win_name }} .add-another-inline-input-list').html('');

            }
        };

        {% if form.is_valid %}

        {% if return_display_name %}
        dismissAddAnotherPopup(win, '{{ form.inst.id }}', '{{ form.inst.get_display_name }}');
        {% else %}
        dismissAddAnotherPopup(win, '{{ form.inst.id }}', '{{ form.inst.id|organization_render_reference:1|safe }}');
        {% endif %}

        {% else %}


        $('.field-inline-{{ win_name }} .add-another-inline-input-list .btn-cancel').click(function (e) {
            e.preventDefault();
            $('.field-inline-{{ win_name }} .add-another-inline-input-list').html('');
            $('.field-inline-{{ win_name }} .inline_overlay').remove();
        });

        $('.field-inline-{{ win_name }} .add-another-inline-input-list .btn-primary').click(function (e) {
            e.preventDefault();

            var input_list_container = $(this).parents('.add-another-inline-input-list');
            var input_list = input_list_container.find('[name]');

            var params = {'_inline': '1'};
            input_list.each(function () {
                if ($(this).attr('type') == 'checkbox') {
                    params[$(this).attr('name')] = 0+$(this).prop('checked');
                }
                else if ($(this).attr('type') == 'radio') {
                    if ($(this).prop('checked')) {
                        params[$(this).attr('name')] = $(this).val();
                    }
                }
                else {
                    params[$(this).attr('name')] = $(this).val();
                }



            });

            var post_url = '{% if form.is_new %}{% url 'organization_inline_create' %}{% else %}{% url 'organization_inline_edit' form.inst.id %}{% endif %}';


            input_list_container.load(post_url, params);

            $('.field-inline-{{ win_name }} .inline_overlay').remove();


        });

        $('.field-inline-{{ win_name }} .inline-reference-wrapper').append('<div class="inline_overlay"></div>');

        {% endif %}


        // confirm delete
        /*
        $('.btn-delete').popConfirm({
            title: "{% trans "Delete Item" %}",
            content: "{% trans "Are you sure you want to delete this item?" %}",
            placement: "top"
        });
        */

        {% if request_inline %}

        var type_of_organization = $('.field-inline-{{ win_name }} input[name=type_of_organization]');

        /*
        if (type_of_organization.length) {
            type_of_organization.each(function () {
                $(this).prettyCheckable();
            });

        }
        */
        {% endif %}

        {% if required_contact %}
        $('#inline-contact-tel-{{ win_name }} .add_more').click(function() {

            var selector = '#' + $(this).attr('id').replace('_add_more', '');
            var type = selector.replace('#id_', '')

            selector = '#inline-contact-tel-{{ win_name }} ' + selector + '>:last'

            var newElement = $(selector).clone(true);
            var total = $('#id_' + type + '-TOTAL_FORMS').val();
            newElement.find(':input').each(function() {
                var name = $(this).attr('name').replace('-' + (total-1) + '-','-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            });
            newElement.find('label').each(function() {
                var newFor = $(this).attr('for').replace('-' + (total-1) + '-','-' + total + '-');
                $(this).attr('for', newFor);
            });
            total++;
            $('#inline-contact-tel-{{ win_name }} #id_' + type + '-TOTAL_FORMS').val(total);
            $(selector).after(newElement);

        });
        {% endif %}


    }) (jQuery);

</script>