api/urls.py
from django.conf.urls import patterns, include
from tastypie.api import Api

from api.resources import *


v1_api = Api(api_name='v1')

# Taxonomy
v1_api.register(TopicResource())
v1_api.register(ArticleCategoryItemResource())
v1_api.register(TypeOfNeedResource())
v1_api.register(TypeOfSupportResource())
v1_api.register(InterestResource())
v1_api.register(UserRoleResource())
v1_api.register(CountryResource())
v1_api.register(OrganizationTypeResource())
v1_api.register(InvestorTypeResource())
v1_api.register(OrganizationProductLaunchResource())
v1_api.register(OrganizationFundingResource())
v1_api.register(OrganizationGrowthStageResource())

############## New For 2018 ######################
v1_api.register(ProgramTypeResource())
v1_api.register(TypeOfOfficeResource())
v1_api.register(TypeOfFocusSectorResource())
v1_api.register(TypeOfFocusIndustryResource())
v1_api.register(TypeOfStageOfParticipantResource())
v1_api.register(TypeOfInvestmentResource())
v1_api.register(TypeOfInvestmentStageResource())
v1_api.register(TypeOfFundingResource())
v1_api.register(TypeOfBatchResource())
v1_api.register(TypeOfFinancialSourceResource())
v1_api.register(TypeOfAssistantshipResource())
v1_api.register(TypeOfAttachmentResource())
v1_api.register(JobRoleResource())
v1_api.register(LocationResource())

# Account
v1_api.register(UserResource())
v1_api.register(PartyLiteResource())
v1_api.register(PartyResource())

# Organization
v1_api.register(OrganizationResource())
v1_api.register(ProgramResource())
v1_api.register(JobResource())
v1_api.register(UserApplyJobResource())
v1_api.register(OrganizationJobsResource())
v1_api.register(SkillResource())
v1_api.register(JobTagResource())
v1_api.register(OrganizationStaffResource())


# Relation
v1_api.register(OrganizationHasPeopleResource())
v1_api.register(PartySupportPartyResource())
v1_api.register(PartyInvestPartyResource())
v1_api.register(PartyPartnerPartyResource())
v1_api.register(PartyFollowPartyResource())
v1_api.register(PartyContactPartyResource())
v1_api.register(PartyTestifyPartyResource())
v1_api.register(OrganizationParticipateResource())
v1_api.register(PartyInviteTestifyPartyResource())
v1_api.register(PartyReceivedFundingPartyResource())
v1_api.register(PartyReceivedInvestingPartyResource())
v1_api.register(PartyLoveResource())
v1_api.register(UserExperienceOrganizationResource())

# Party
v1_api.register(PortfolioResource())
v1_api.register(PartyFollowingResource())

#CMS
v1_api.register(NewsResource())
v1_api.register(EventResource())
v1_api.register(NewsTagResource())
v1_api.register(EventTagResource())


# Notification
v1_api.register(VerbResource())
v1_api.register(NotificationResource())
v1_api.register(RequestResource())

v1_api.register(HappeningResource())

v1_api.register(SearchResource())

urlpatterns = patterns('',
    (r'', include(v1_api.urls)),
)

asip/urls.py
import os
import autocomplete_light
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse
from django.views.generic import TemplateView

from django.conf.urls.i18n import i18n_patterns

autocomplete_light.autodiscover()
admin.autodiscover()

CUSTOM_ENABLED = True
try:
    import custom.urls
except ImportError:
    CUSTOM_ENABLED = False


# urlpatterns = i18n_patterns('', # not trans now
urlpatterns = patterns('',
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^tagging_autocomplete_tagit/', include('tagging_autocomplete_tagit.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^files-widget/', include('files_widget.urls')),
    url(r'^account/', include('account.urls', app_name='accoount')),
    url(r'^people/', include('account.people_urls', app_name='account')),
    url(r'^organization/', include('organization.urls', app_name='organization')),
    url(r'^people/', include('account.people_urls', app_name='account')),
    url(r'^forum/', include('forum.urls', app_name='forum')),

    url(r'^api/', include('api.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'', include('notification.urls')),
    url(r'', include('taxonomy.urls', app_name='taxonomy')),

    url(r'', include('organization.job_urls', app_name='organization')),
    url(r'', include('party.urls', app_name='party')),
    url(r'', include('relation.urls', app_name='relation')),
    url(r'', include('cms.urls', app_name='cms')),
    url(r'', include('account.connect_urls', app_name='account')),

    url(r'', include('social_auth.urls')),
    url(r'', include('presentation.urls', app_name='presentation')),
    # No swap order url
    url(r'', include('account.role_urls', app_name='account')),
    url(r'', include('special.urls', app_name='special')),
    url(r'', include('organization.role_urls', app_name='organization')),

)

if CUSTOM_ENABLED:
    # urlpatterns += i18n_patterns('', # not trans now
    urlpatterns += patterns('',

        url(r'', include('custom.urls')),
    )

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
        url(r'^404$', TemplateView.as_view(template_name='404.html')),
        url(r'^500$', TemplateView.as_view(template_name='500.html')),
    )

    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

else:
    urlpatterns += patterns('',
        url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    )


handler403 = 'presentation.views.handler403'

cms/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',

    url(r'^updates/news/create/$', 'cms.views.news_create', name='news_create'),
    url(r'^updates/news/(?P<news_id>\d+)/edit/$', 'cms.views.news_edit', name='news_edit'),

    url(r'^updates/news/(?P<news_permalink>[A-Za-z0-9-_.]+)/(?P<news_id>\d+)/$', 'cms.views.news_detail', name='news_detail'),
    url(r'^updates/news/(?P<news_permalink>[A-Za-z0-9-_.]+)/$', 'cms.views.news_detail', name='news_detail_redirect'),
    url(r'^updates/news/$', 'cms.views.article_list', name='news_list'),

    #================ Article =================
    url(r'^article/create/$', 'cms.views.news_create', name='article_create'),
    url(r'^article/(?P<article_category>[A-Za-z0-9-_.]+)/create/$', 'cms.views.news_create', name='article_create_with_category'),
    url(r'^article/(?P<news_id>\d+)/edit/$', 'cms.views.news_edit', name='article_edit'),

    url(r'^article/(?P<article_category>[A-Za-z0-9-_.]+)/(?P<news_permalink>[A-Za-z0-9-_.]+)/(?P<news_id>\d+)/$', 'cms.views.article_detail', name='article_detail'),
    url(r'^article/news/(?P<news_permalink>[A-Za-z0-9-_.]+)/$', 'cms.views.news_detail', name='news_detail_redirect'),
    url(r'^article/(?P<article_category>[A-Za-z0-9-_.]+)/$', 'cms.views.article_list', name='article_list'),
    #============ Event =======================

    url(r'^updates/event/(?P<event_id>\d+)/edit/$', 'cms.views.event_edit', name='event_edit'),
    url(r'^updates/event/create/$', 'cms.views.event_create', name='event_create'),
    url(r'^updates/event/past/$', 'cms.views.event_past_list', name='event_past_list'),

    url(r'^updates/event/(?P<event_permalink>[A-Za-z0-9-_.]+)/(?P<event_id>\d+)/$', 'cms.views.event_detail', name='event_detail'),
    url(r'^updates/event/(?P<event_permalink>[A-Za-z0-9-_.]+)/$', 'cms.views.event_detail', name='event_detail_redirect'),
    url(r'^updates/event/$', 'cms.views.event_list', name='event_list'),

    url(r'^updates/$', 'cms.views.updates_landing', name='updates_landing'),
)

custom/urls.py
from django.conf.urls import url, patterns

urlpatterns = ()

'''
urlpatterns = patterns('custom.views',

    url(r'^(?P<organization_role_permalink>[A-Za-z0-9-_.]+)/(?P<organization_role_permalink>[A-Za-z0-9-_.]+)/organization/$', 'organization_role_list', name='organization_role_list'),

    url(r'^(?P<organization_role_permalink>[A-Za-z0-9-_.]+)/(?P<organization_permalink>[A-Za-z0-9-_.]+)/(?P<organization_id>\d+)/$',
        'organization_role_detail', name='organization_role_detail'),
    url(r'^(?P<organization_role_permalink>[A-Za-z0-9-_.]+)/(?P<organization_permalink>[A-Za-z0-9-_.]+)/$',
        'organization_role_detail', name='organization_role_detail_redirect'),

)
'''

cms/models.py
import re
from datetime import date
import tagging
from ckeditor.fields import RichTextField
from django.core import validators
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import truncatechars
from django.utils import timezone
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from common.constants import SUMMARY_MAX_LENGTH, STATUS_PENDING, STATUS_PUBLISHED
from common.functions import instance_get_thumbnail
from common.models import PriorityModel, AbstractPermalink
import files_widget

from organization.models import Organization
from party.models import Party
from tagging_autocomplete_tagit.models import TagAutocompleteTagItField
from taxonomy.models import ArticleCategory

USER_MODEL = settings.AUTH_USER_MODEL

class CommonCms(AbstractPermalink):

    title = models.CharField(max_length=255)
    image = files_widget.ImageField(null=True, blank=True)
    summary = models.TextField(null=True, blank=True)
    description = RichTextField(null=True, blank=True)
    topics = models.ManyToManyField('taxonomy.Topic', null=True, blank=True, related_name='cms_topics')
    party_created_by = models.ForeignKey(Party, related_name='cms_party_created_by')
    created_by = models.ForeignKey(USER_MODEL, related_name='cms_created_by')
    published_by = models.ForeignKey(USER_MODEL, related_name='cms_published_by', null=True, blank=True)

    status = models.IntegerField(default=STATUS_PUBLISHED)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    changed = models.DateTimeField(auto_now=True, null=True, blank=True)
    published = models.DateTimeField(null=True, blank=True)

    is_promoted = models.BooleanField(default=True)

    facebook_url = models.URLField(max_length=255, null=True, blank=True)
    twitter_url = models.URLField(max_length=255, null=True, blank=True)
    homepage_url = models.URLField(max_length=1024, null=True, blank=True)

    uuid = models.CharField(max_length=255, null=True, blank=True)



    class Meta:
        ordering = ['-id']

    def get_display_name(self):
        return self.title or ''

    def get_thumbnail(self):
        return instance_get_thumbnail(self, crop=None, size='x360')

    def get_thumbnail_in_primary(self):
        return instance_get_thumbnail(self, size='150x150', crop=None, upscale=False)

    def get_summary(self):
        return truncatechars(self.summary or self.description or '', SUMMARY_MAX_LENGTH)

    def get_absolute_url(self):

        if hasattr(self, 'news') and self.news:
            return self.news.get_absolute_url()
        elif hasattr(self, 'event') and self.event:
            return self.event.get_absolute_url()

        return ''

    def save(self, *args, **kwargs):
        super(CommonCms, self).save(*args, **kwargs)




class News(CommonCms):
    # relation
    #organization = models.ForeignKey(Organization, related_name='news_organization', null=True, blank=True)
    # Taxonomy
    ARTICLE_TYPE_CHOICES = (
        ('news', _('News')),
        ('knowledge-tools', _('Knowledge & Tools')),
    )
    # deprecate
    article_category = models.CharField(max_length=255, choices=ARTICLE_TYPE_CHOICES, default='news')

    categories = models.ManyToManyField('taxonomy.ArticleCategory', null=True, blank=True, related_name='cms_categories')

    tags = TagAutocompleteTagItField(max_tags=False, null=True, blank=True, max_length=2048)

    files = files_widget.XFilesField(verbose_name='File Attachment', null=True, blank=True)


    def get_absolute_url(self):

        first_category = None
        try:
            first_category = self.categories.filter(level=0).first()
        except (ArticleCategory.DoesNotExist, ValueError):

            try:
                first_category = self._categories[0]
            except (AttributeError, IndexError):
                pass

        if first_category:
            if first_category.permalink == 'news':
                return reverse('news_detail', args=[self.permalink, self.id])
            else:
                return reverse('article_detail', args=[first_category.permalink, self.permalink, self.id])

        # deprecate
        if self.article_category == 'news':
            return reverse('news_detail', args=[self.permalink, self.id])
        else:
            return reverse('article_detail', args=[self.article_category, self.permalink, self.id])

    def get_files(self):
        files = []
        if self.files:
            files = [ settings.MEDIA_URL + path  for path in self.files.split('\n')]

        return files


tagging.register(News, tag_descriptor_attr='tag_set')


class Event(CommonCms):

    #organization = models.ForeignKey(Organization, related_name='event_organization', null=True, blank=True)
    location = models.TextField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True, default=timezone.now)
    end_date = models.DateField(null=True, blank=True)
    time = models.CharField(max_length=255, null=True, blank=True)
    phone = models.TextField(null=True, blank=True)
    email = models.EmailField(
        max_length=255,
        null=True,
        blank=True
    )

    tags = TagAutocompleteTagItField(max_tags=False, null=True, blank=True, max_length=2048)


    def get_absolute_url(self):
        return reverse('event_detail', args=[self.permalink, self.id])

    def get_phones(self):
        return [phone.strip() for phone in self.phone.split(',')]

tagging.register(Event, tag_descriptor_attr='tag_set')

templates/cms/event/form.html
{% extends 'base_single.html' %}
{% load i18n %}
{% load staticfiles %}

{% block title %}
{% if form.is_new %}{% trans "Create" %} {%  trans "Event" %}{% else %}{% trans "Edit" %} {{ form.inst.title }}{% endif %}
{% if not form.is_new and not request_popup%}
<a href="{{ form.inst.get_absolute_url }}" class="btn btn-default btn-xs btn-view">
    <span class="glyphicon glyphicon-eye-open"></span> {% trans "View result" %}
</a>
{% endif %}
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}
{% block css %}

{% endblock %}

{% block content_class %} content-smart{% endblock %}


{% block breadcrumb %}
<li class="active">{% trans "Add Event" %}</li>
{% endblock %}


{% block content %}

<form method="post" class="form-horizontal" role="form" enctype="multipart/form-data" ng-non-bindable>
    {% csrf_token %}

    {% if form.non_field_errors %}
    <div class="errors alert alert-danger">{{ form.non_field_errors }}</div>
    {% endif %}


    <div class="controls form-group">
        <label for="id_title" class="field-container control-label col-sm-3">{% trans "Title" %} *</label>
        <div class="field-container col-sm-7">
            <span id="generate-permalink">
                {{ form.title}}
            </span>
{#            <span class="help-block">#}
{#            {{ form.title.help_text }}#}
{#            </span>#}
            {% if form.title.errors %}
            <div class="errors alert alert-danger">{{ form.title.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group permalink-inline">
        <div class="field-container control-label col-sm-3">
            <label for="id_permalink" class="control-label">{% trans "Permalink" %} <span class="label-required-ico">*</span></label>
        </div>
        <div class="field-container col-sm-7">

            <span id="id_permalink_readonly" class="form-control">{{ form.permalink.value|default_if_none:'' }}</span>
            <a id="edit-permalink" href="#id_permalink">{% trans "edit" %}</a>

            <input id="id_permalink" name="permalink" type="text" class="form-control" value="{{ form.permalink.value|default_if_none:'' }}">
            <span class="help-block">
                {% blocktrans with inst_type='event' %}This field represent your {{ inst_type }} url in this website.{% endblocktrans %}<br />
                {{ form.permalink.help_text }}
            </span>
            {% if form.permalink.errors %}
            <div class="errors alert alert-danger">{{ form.permalink.errors }}</div>
            {% endif %}
        </div>
    </div>


    <div class="controls form-group">
        <label for="id_image" class="field-container control-label col-sm-3">{% trans "Image" %}</label>
        <div class="field-container col-sm-7">
            {{ form.image }}
            <span class="help-block">
            {{ form.image.help_text }}
            </span>
            {% if form.image.errors %}
            <div class="errors alert alert-danger">{{ form.image.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_location" class="field-container control-label col-sm-3">{% trans "Location" %} </label>
        <div class="field-container col-sm-7">
            {{ form.location }}
                <span class="help-block">
                    {{ form.location.help_text }}
                </span>
            {% if form.location.errors %}
            <div class="errors alert alert-danger">{{ form.location.errors }}</div>
            {% endif %}
        </div>
    </div>
    <div class="controls form-group">
        <label for="id_start_date" class="field-container control-label col-sm-3">{% trans "Start date" %} *</label>
        <div class="field-container col-sm-7">
            {{ form.start_date }}
            <span class="help-block">
            {{ form.start_date.help_text }}
            </span>
            {% if form.start_date.errors %}
            <div class="errors alert alert-danger">{{ form.start_date.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_end_date" class="field-container control-label col-sm-3">{% trans "End date" %} </label>
        <div class="field-container col-sm-7">
            {{ form.end_date }}
            <span class="help-block">
            {{ form.end_date.help_text }}
            </span>
            {% if form.end_date.errors %}
            <br />
            <div class="errors alert alert-danger">{{ form.end_date.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_time" class="field-container control-label col-sm-3">{% trans "Time" %} </label>
        <div class="field-container col-sm-7">
            {{ form.time}}
            <span class="help-block">
            {{ form.time.help_text }}
            </span>
            {% if form.time.errors %}
            <div class="errors alert alert-danger">{{ form.time.errors }}</div>
            {% endif %}
        </div>
    </div>

    <!--  Todo relation later
        <div class="controls form-group">
            <label for="id_organization" class="field-container control-label">{% trans "Organization" %}</label>
            {{ form.organization }}
            {% if form.organization.errors %}
            <div class="errors alert alert-danger">{{ form.organization.errors }}</div>
            {% endif %}
        </div>
    -->

    <div class="controls form-group">
        <label for="id_summary" class="field-container control-label col-sm-3">{% trans "Summary" %} </label>
        <div class="field-container col-sm-7">
            {{ form.summary }}
            <span class="help-block">
                {% blocktrans with maxlength=form.summary.field.widget.attrs.maxlength %}Short detail in {{ maxlength }} characters{% endblocktrans %}
            </span>
            {% if form.summary.errors %}
            <div class="errors alert alert-danger">{{ form.summary.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_description" class="field-container control-label col-sm-3">{% trans "Content" %} </label>
        <div class="field-container col-sm-7">
            {{ form.description }}
            <span class="help-block">
            {{ form.description.help_text }}
            </span>
            {% if form.description.errors %}
            <div class="errors alert alert-danger">{{ form.description.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_topics" class="field-container control-label col-sm-3">{% trans "Topic" %} *</label>
        <div class="checkbox col-sm-7">
            <ul>
                {% for topic in form.topics %}
                <li>
                    <span class="choice-item">
                        {{ topic.tag }}
                        <label for="id_topics_{{ topic.index }}">{{ topic.choice_label }}</label>
                    </span>
                </li>
                {% endfor %}
            </ul>

            {% if form.topics.errors %}
            <div class="errors alert alert-danger">{{ form.topics.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_tags" class="col-sm-3 control-label">{% trans "Tags" %}</label>
        <div class="col-sm-7">
            {{ form.tags }}
            <span class="help-block">
            {{ form.tags.help_text }}
            </span>
            {% if form.tags.errors %}
            <div class="errors alert alert-danger">{{ form.tags.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">

        <label for="id_in_the_news" class="col-sm-3 control-label">{% trans "Add organizations/people in the event" %}</label>
        <div class="col-sm-7">
            {{ form.in_the_news }}
            <span class="help-block">
                {% trans "Enter organizations/people name to display on your event." %}
            </span>

            {% if form.in_the_news.errors %}
            <div class="errors alert alert-danger">{{ form.in_the_news.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <br /><br />
        <h3 class="col-sm-3 control-label">{% trans "Contact of Event’s Organizer" %}</h3>
        <hr class="col-sm-7 hidden-xs" />
        <br /><br class="hidden-xs"/>
    </div>

    <div class="controls form-group">
        <label for="id_phone" class="field-container control-label col-sm-3">{% trans "Phone number" %} </label>
        <div class="field-container col-sm-7">
            {{ form.phone}}
            <span class="help-block">
            {{ form.phone.help_text }}
            </span>
            {% if form.phone.errors %}
            <div class="errors alert alert-danger">{{ form.phone.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_email" class="col-sm-3 control-label">{% trans "Email" %} </label>
        <div class="col-sm-7">
            <input id="id_email" name="email" type="email" class="form-control" value="{{ form.email.value|default_if_none:'' }}" >
            <span class="help-block">
            {{ form.email.help_text }}
            </span>
            {% if form.email.errors %}
            <div class="errors alert alert-danger">{{ form.email.errors }}</div>
            {% endif %}
        </div>
    </div>


    <div class="controls form-group">
        <label for="id_facebook_url" class="col-sm-3 control-label">{% trans "Facebook URL" %}</label>
        <div class="col-sm-7">
            <input id="id_facebook_url" name="facebook_url" type="text" class="form-control" value="{{ form.facebook_url.value|default_if_none:'' }}">
            <span class="help-block">
            {{ form.facebook_url.help_text }}
            </span>
            {% if form.facebook_url.errors %}
            <div class="errors alert alert-danger">{{ form.facebook_url.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_twitter_url" class="col-sm-3 control-label">{% trans "Twitter URL" %}</label>
        <div class="col-sm-7">
            <input id="id_twitter_url" name="twitter_url" type="text" class="form-control" value="{{ form.twitter_url.value|default_if_none:'' }}">
            <span class="help-block">
            {{ form.twitter_url.help_text }}
            </span>
            {% if form.twitter_url.errors %}
            <div class="errors alert alert-danger">{{ form.twitter_url.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_homepage_url" class="col-sm-3 control-label">{% trans "Homepage URL" %}</label>
        <div class="col-sm-7">
            <input id="id_homepage_url" name="homepage_url" type="text" class="form-control" value="{{ form.homepage_url.value|default_if_none:'' }}">
            <span class="help-block">
            {{ form.homepage_url.help_text }}
            </span>
            {% if form.homepage_url.errors %}
            <div class="errors alert alert-danger">{{ form.homepage_url.errors }}</div>
            {% endif %}
        </div>
    </div>

    {% if is_staff or form.inst.is_promoted %}
    <div class="controls form-group">

        <label class="col-sm-3 control-label">{% trans "Promote?" %}</label>
        <div class="col-sm-7">
            <span class="choice-item">
                {{ form.is_promoted }}
                <label for="id_is_promoted">{% trans "Promote to Front Page" %}</label>
            </span>
            {% if form.is_promoted.errors %}
            <div class="errors alert alert-danger">{{ form.is_promoted.errors }}</div>
            {% endif %}
        </div>
    </div>
    {% endif %}


    <div class="controls form-group group-action">

        <div class="col-sm-offset-3 col-sm-7 form-action">
            <button class="btn btn-primary btn-orange{% if form.is_new %} btn-submit{% endif %}" type="submit">{% if form.is_new %}{% trans "Create" %}{% else %}{% trans "Save changes" %}{% endif %}</button>
            <a href="." target="_self" class="btn btn-default btn-cancel">{% trans "Cancel" %}</a>
        </div>

        {% if not form.is_new and logged_in_party.id == user.id %}
        <a class="btn btn-md btn-delete" href="{% url 'presentation_delete' 'cms' 'News' form.inst.id %}">
            <span class="glyphicon glyphicon-remove icostartup icon-delete"></span>
            {% trans "Delete" %}
        </a>
        {% endif %}

    </div>

</form>

<input type="hidden" name="control_permalink" value="1"/>
<input type="hidden" name="prevent_scroll_reload" value="1"/>
<input type="hidden" name="is_new" value="{% if form.is_new %}1{% else %}0{% endif %}"/>


{% endblock %}