api/urls.py
from django.conf.urls import patterns, include
from tastypie.api import Api

from api.resources import *


v1_api = Api(api_name='v1')

# Taxonomy
v1_api.register(TopicResource())
v1_api.register(ArticleCategoryItemResource())
v1_api.register(TypeOfNeedResource())
v1_api.register(TypeOfSupportResource())
v1_api.register(InterestResource())
v1_api.register(UserRoleResource())
v1_api.register(CountryResource())
v1_api.register(OrganizationTypeResource())
v1_api.register(InvestorTypeResource())
v1_api.register(OrganizationProductLaunchResource())
v1_api.register(OrganizationFundingResource())
v1_api.register(OrganizationGrowthStageResource())

############## New For 2018 ######################
v1_api.register(ProgramTypeResource())
v1_api.register(TypeOfOfficeResource())
v1_api.register(TypeOfFocusSectorResource())
v1_api.register(TypeOfFocusIndustryResource())
v1_api.register(TypeOfStageOfParticipantResource())
v1_api.register(TypeOfInvestmentResource())
v1_api.register(TypeOfInvestmentStageResource())
v1_api.register(TypeOfFundingResource())
v1_api.register(TypeOfBatchResource())
v1_api.register(TypeOfFinancialSourceResource())
v1_api.register(TypeOfAssistantshipResource())
v1_api.register(TypeOfAttachmentResource())
v1_api.register(JobRoleResource())
v1_api.register(LocationResource())

# Account
v1_api.register(UserResource())
v1_api.register(PartyLiteResource())
v1_api.register(PartyResource())

# Organization
v1_api.register(OrganizationResource())
v1_api.register(ProgramResource())
v1_api.register(JobResource())
v1_api.register(UserApplyJobResource())
v1_api.register(OrganizationJobsResource())
v1_api.register(SkillResource())
v1_api.register(JobTagResource())
v1_api.register(OrganizationStaffResource())


# Relation
v1_api.register(OrganizationHasPeopleResource())
v1_api.register(PartySupportPartyResource())
v1_api.register(PartyInvestPartyResource())
v1_api.register(PartyPartnerPartyResource())
v1_api.register(PartyFollowPartyResource())
v1_api.register(PartyContactPartyResource())
v1_api.register(PartyTestifyPartyResource())
v1_api.register(OrganizationParticipateResource())
v1_api.register(PartyInviteTestifyPartyResource())
v1_api.register(PartyReceivedFundingPartyResource())
v1_api.register(PartyReceivedInvestingPartyResource())
v1_api.register(PartyLoveResource())
v1_api.register(UserExperienceOrganizationResource())

# Party
v1_api.register(PortfolioResource())
v1_api.register(PartyFollowingResource())

#CMS
v1_api.register(NewsResource())
v1_api.register(EventResource())
v1_api.register(NewsTagResource())
v1_api.register(EventTagResource())


# Notification
v1_api.register(VerbResource())
v1_api.register(NotificationResource())
v1_api.register(RequestResource())

v1_api.register(HappeningResource())

v1_api.register(SearchResource())

urlpatterns = patterns('',
    (r'', include(v1_api.urls)),
)

asip/urls.py
import os
import autocomplete_light
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse
from django.views.generic import TemplateView

from django.conf.urls.i18n import i18n_patterns

autocomplete_light.autodiscover()
admin.autodiscover()

CUSTOM_ENABLED = True
try:
    import custom.urls
except ImportError:
    CUSTOM_ENABLED = False


# urlpatterns = i18n_patterns('', # not trans now
urlpatterns = patterns('',
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^tagging_autocomplete_tagit/', include('tagging_autocomplete_tagit.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^files-widget/', include('files_widget.urls')),
    url(r'^account/', include('account.urls', app_name='accoount')),
    url(r'^people/', include('account.people_urls', app_name='account')),
    url(r'^organization/', include('organization.urls', app_name='organization')),
    url(r'^people/', include('account.people_urls', app_name='account')),
    url(r'^forum/', include('forum.urls', app_name='forum')),

    url(r'^api/', include('api.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'', include('notification.urls')),
    url(r'', include('taxonomy.urls', app_name='taxonomy')),

    url(r'', include('organization.job_urls', app_name='organization')),
    url(r'', include('party.urls', app_name='party')),
    url(r'', include('relation.urls', app_name='relation')),
    url(r'', include('cms.urls', app_name='cms')),
    url(r'', include('account.connect_urls', app_name='account')),

    url(r'', include('social_auth.urls')),
    url(r'', include('presentation.urls', app_name='presentation')),
    # No swap order url
    url(r'', include('account.role_urls', app_name='account')),
    url(r'', include('special.urls', app_name='special')),
    url(r'', include('organization.role_urls', app_name='organization')),

)

if CUSTOM_ENABLED:
    # urlpatterns += i18n_patterns('', # not trans now
    urlpatterns += patterns('',

        url(r'', include('custom.urls')),
    )

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
        url(r'^404$', TemplateView.as_view(template_name='404.html')),
        url(r'^500$', TemplateView.as_view(template_name='500.html')),
    )

    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

else:
    urlpatterns += patterns('',
        url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    )


handler403 = 'presentation.views.handler403'

custom/urls.py
from django.conf.urls import url, patterns

urlpatterns = ()

'''
urlpatterns = patterns('custom.views',

    url(r'^(?P<organization_role_permalink>[A-Za-z0-9-_.]+)/(?P<organization_role_permalink>[A-Za-z0-9-_.]+)/organization/$', 'organization_role_list', name='organization_role_list'),

    url(r'^(?P<organization_role_permalink>[A-Za-z0-9-_.]+)/(?P<organization_permalink>[A-Za-z0-9-_.]+)/(?P<organization_id>\d+)/$',
        'organization_role_detail', name='organization_role_detail'),
    url(r'^(?P<organization_role_permalink>[A-Za-z0-9-_.]+)/(?P<organization_permalink>[A-Za-z0-9-_.]+)/$',
        'organization_role_detail', name='organization_role_detail_redirect'),

)
'''

relation/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('relation.views',
    url(r'^experience/(?P<experience_id>\d+)/edit/$', 'experience_edit', name='user_experience_organization_edit'),
    url(r'^experience/create/$', 'experience_create', name='user_experience_organization_create'),
    url(r'^received_funding/(?P<received_funding_id>\d+)/edit/$', 'received_funding_edit',
       name='party_received_funding_party_edit'),
    url(r'^received_funding/create/$', 'received_funding_create', name='party_received_funding_party_create'),

    url(r'^invite_testify/create/(?P<party_id>\d+)/$', 'invite_testify_create', name='party_invite_testify_party_create'),


)

relation/models.py
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import truncatechars
from django.utils.translation import ugettext as _

from common.constants import STATUS_CHOICES, STATUS_PENDING, SUMMARY_MAX_LENGTH, STATUS_PUBLISHED, STATUS_DELETED, STATUS_REJECTED
from common.models import PriorityModel, CommonModel, CachedModel
from djmoney.models.fields import MoneyField

RELATION_STATUS_CHOICES = STATUS_CHOICES + ((STATUS_DELETED, 'Deleted'), )

class BaseRelation(CommonModel, PriorityModel, CachedModel):
    STATUS_PENDING = STATUS_PENDING
    STATUS_PUBLISHED = STATUS_PUBLISHED
    STATUS_DELETED = STATUS_DELETED
    STATUS_REJECTED = STATUS_REJECTED
    RELATION_STATUS_CHOICES = RELATION_STATUS_CHOICES

    created = models.DateTimeField(auto_now_add=True)
    changed = models.DateTimeField(auto_now=True)
    data = models.TextField(null=True, blank=True)

    origin = None

    NOTIFICATION_CHECK_CRAZY_CREATED = True
    NOTIFICATION_VERB_DISPLAY = _('Not implement %s')
    NOTIFICATION_PRIVATE = False

    REQUIRED_APPROVAL = True

    CROSS_TARGET = False
    CLAIM_APPROVE = False

    class Meta:
        abstract = True


    def save(self, *args, **kwargs):

        if hasattr(self, 'src') and hasattr(self, 'dst'):

            src = self.src.party_ptr if hasattr(self.src, 'party_ptr') else self.src
            dst = self.dst.party_ptr if hasattr(self.dst, 'party_ptr') else self.dst
            if src == dst:
                raise PermissionDenied()

            super(BaseRelation, self).save(*args, **kwargs)

            if hasattr(self, 'rebuild_total_fields'):

                src = src.__class__.objects.get(id=src.id)
                dst = dst.__class__.objects.get(id=dst.id)
                src.build_total(field_names=self.rebuild_total_fields)
                dst.build_total(field_names=self.rebuild_total_fields)

        else:
            super(BaseRelation, self).save(*args, **kwargs)


        from notification.models import Notification

        if self.id:
            if self.status == STATUS_REJECTED:
                for notification in Notification.objects.filter(target_id=self.id, is_system=True):
                    notification.status = STATUS_REJECTED
                    notification.save()

            elif self.status == STATUS_PUBLISHED:
                for notification in Notification.objects.filter(target_id=self.id, is_system=True):
                    notification.status = STATUS_PUBLISHED
                    notification.save()


    def delete(self, *args, **kwargs):

        if hasattr(self, 'src') and hasattr(self, 'dst'):
            src = self.src.party_ptr if hasattr(self.src, 'party_ptr') else self.src
            dst = self.dst.party_ptr if hasattr(self.dst, 'party_ptr') else self.dst

            super(BaseRelation, self).delete(*args, **kwargs)

            if hasattr(self, 'rebuild_total_fields'):
                src = src.__class__.objects.get(id=src.id)
                dst = dst.__class__.objects.get(id=dst.id)
                src.build_total(field_names=self.rebuild_total_fields)
                dst.build_total(field_names=self.rebuild_total_fields)

        else:
            super(BaseRelation, self).save(*args, **kwargs)



class OrganizationHasPeople(BaseRelation):
    src = models.ForeignKey('organization.Organization', related_name='organization_has_people_src')
    dst = models.ForeignKey('account.User', related_name='organization_has_people_dst')

    status = models.IntegerField(choices=RELATION_STATUS_CHOICES, default=STATUS_PENDING)

    NOTIFICATION_VERB_DISPLAY = _('adds %s as people in organization')
    REQUEST_VERB_DISPLAY = _('Add people to organization')

class PartyPartnerParty(BaseRelation):
    src = models.ForeignKey('party.Party', related_name='partner_src')
    dst = models.ForeignKey('party.Party', related_name='partner_dst')

    status = models.IntegerField(choices=RELATION_STATUS_CHOICES, default=STATUS_PENDING)

    NOTIFICATION_VERB_DISPLAY = _('add %s as partner')
    CROSS_TARGET = True
    REQUEST_VERB_DISPLAY = 'Partner/Client'

    CLAIM_APPROVE = True


class PartySupportParty(BaseRelation):
    src = models.ForeignKey('party.Party', related_name='support_src')
    dst = models.ForeignKey('party.Party', related_name='support_dst')

    status = models.IntegerField(choices=RELATION_STATUS_CHOICES, default=STATUS_PENDING)

    swap = models.NullBooleanField(null=True, blank=True)

    NOTIFICATION_VERB_DISPLAY = _('gives support to %s')
    NOTIFICATION_VERB_SWAP_DISPLAY = _('is supported by %s')
    REQUEST_VERB_DISPLAY = 'Give support'
    REQUEST_VERB_SWAP_DISPLAY = 'Supported by'


class PartyInvestParty(BaseRelation):
    src = models.ForeignKey('party.Party', related_name='invest_src')
    dst = models.ForeignKey('party.Party', related_name='invest_dst')

    status = models.IntegerField(choices=RELATION_STATUS_CHOICES, default=STATUS_PENDING)

    swap = models.NullBooleanField(null=True, blank=True)

    NOTIFICATION_VERB_DISPLAY = _('invest in %s')
    NOTIFICATION_VERB_SWAP_DISPLAY = _('is invested by %s')

    REQUEST_VERB_DISPLAY = 'Invest to'
    REQUEST_VERB_SWAP_DISPLAY = 'Invested by'


# Has pagination not map m2m fields
class PartyFollowParty(BaseRelation):
    src = models.ForeignKey('party.Party', related_name='follow_src')
    dst = models.ForeignKey('party.Party', related_name='follow_dst')

    status = models.IntegerField(choices=RELATION_STATUS_CHOICES, default=STATUS_PUBLISHED)

    rebuild_total_fields = ['total_following', 'total_follower', 'popular']

    NOTIFICATION_CHECK_CRAZY_CREATED = False
    NOTIFICATION_VERB_DISPLAY = _('is now following %s')
    REQUEST_VERB_DISPLAY = _('Follow')

    REQUIRED_APPROVAL = False


# Has pagination not map m2m fields
class PartyContactParty(BaseRelation):
    STATUS_UNREAD = 0
    STATUS_READ = 1
    READ_STATUS_CHOICES = (
        (STATUS_UNREAD, 'Unread'),
        (STATUS_READ, 'Read'),
    )

    src = models.ForeignKey('party.Party', related_name='contact_src')
    dst = models.ForeignKey('party.Party', related_name='contact_dst')

    status = models.IntegerField(choices=READ_STATUS_CHOICES, default=STATUS_UNREAD)

    system = models.NullBooleanField(null=True, blank=True)

    NOTIFICATION_CHECK_CRAZY_CREATED = False
    NOTIFICATION_VERB_DISPLAY = _('sends a message to %s')
    NOTIFICATION_DATA_DISPLAY = _('Active as this organization to see the message')
    NOTIFICATION_PRIVATE = True
    NOTIFICATION_VERB_SYSTEM_DISPLAY = _('request more financial information to %s')

    REQUIRED_APPROVAL = False
    REQUEST_VERB_DISPLAY = 'Message'

    def get_absolute_url(self):
        return '%s?next=%s' % (reverse('party_activate', args=[self.dst.id]), reverse('message_list'))


# Has pagination not map m2m fields
class PartyTestifyParty(BaseRelation):
    POINT_CHOICES = (
        (0, 0),
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5)
    )
    src = models.ForeignKey('party.Party', related_name='testify_src')
    dst = models.ForeignKey('party.Party', related_name='testify_dst')
    point = models.IntegerField(choices=POINT_CHOICES, default=0)

    status = models.IntegerField(choices=RELATION_STATUS_CHOICES, default=STATUS_PENDING)

    rebuild_total_fields = ['total_testify', 'popular']

    NOTIFICATION_CHECK_CRAZY_CREATED = False
    NOTIFICATION_VERB_DISPLAY = _('gives testimonial to %s')
    REQUEST_VERB_DISPLAY = _('Testimonial')


    def get_absolute_url(self):
        return '%s##testimonials' % self.dst.get_absolute_url()


class UserExperienceOrganization(BaseRelation):

    src = models.ForeignKey('account.User', blank=True, null=True, related_name='experience_src')
    dst = models.ForeignKey('organization.Organization', related_name='experience_dst')

    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)

    status = models.IntegerField(choices=RELATION_STATUS_CHOICES, default=STATUS_PENDING)

    NOTIFICATION_VERB_DISPLAY = _('now works at %s')
    REQUEST_VERB_DISPLAY = _('Experience')
    NOTIFICATION_DATE_FIELD = 'start_date'


    def get_summary(self):
        return truncatechars(self.description, SUMMARY_MAX_LENGTH)


class PartyReceivedFundingParty(BaseRelation):

    src = models.ForeignKey('party.Party', blank=True, null=True, related_name='received_funding_src')
    dst = models.ForeignKey('party.Party', blank=True, null=True, related_name='received_funding_dst')

    amount = models.DecimalField(
        max_digits=19,
        decimal_places=2,
        null=True,
        blank=True,
    ) #deprecated
    money_amount = MoneyField(null=True, blank=True, max_digits=19, decimal_places=2, default_currency='THB')

    title = models.CharField(null=True, blank=True, max_length=255)

    date = models.DateTimeField(null=True, blank=True)

    status = models.IntegerField(choices=RELATION_STATUS_CHOICES, default=STATUS_PENDING)

    swap = models.NullBooleanField(null=True, blank=True)


    NOTIFICATION_VERB_DISPLAY = _('receives funding from %s')
    NOTIFICATION_VERB_SWAP_DISPLAY = _('gives funding to %s')
    NOTIFICATION_DATE_FIELD = 'date'

    NOTIFICATION_DATA_FIELD = 'money_amount'
    NOTIFICATION_DATA_FIELD_IS_INTEGER = False
    #NOTIFICATION_DATA_SUFFIX = settings.CURRENCY
    REQUEST_VERB_DISPLAY = 'Receives Funding'
    REQUEST_VERB_SWAP_DISPLAY = 'Gives Funding'

    CLAIM_APPROVE = True


    def get_absolute_url(self):
        return '%s##happening' % self.src.get_absolute_url()


class PartyReceivedInvestingParty(BaseRelation):

templates/relation/experience/form.html
{% extends 'base_single.html' %}
{% load i18n %}
{% load staticfiles %}

{% block content_class %} content-smart bg-white{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}
{% block css %}

{% endblock %}


{% block title %}
{% if form.is_new %}{% trans "Create" %}{% else %}{% trans "Edit" %}{% endif %} Your Experience
{% endblock %}

{% block content %}

<form method="post" class="form-horizontal" role="form" enctype="multipart/form-data" ng-non-bindable>
    {% csrf_token %}

    {% if form.non_field_errors %}
    <div class="errors alert alert-danger">{{ form.non_field_errors }}</div>
    {% endif %}

    <div class="controls form-group">

        <label for="id_dst" class="field-container control-label col-sm-3">{% trans "Organization" %} *</label>
        <div class="field-container-no-overflow field-inline-id_dst col-sm-7">

            <div class="inline-reference-container">
                <div class="inline-reference-wrapper">

                    {{ form.dst }}

                    <div class="inline-create-link-wrapper">
                        {% trans "or" %}
                        <span class="glyphicon glyphicon-plus icostartup icon-plus"></span>
                        <a href="{% url 'organization_inline_create' %}?_inline=1&is_mockup=1" class="add-another-inline" id="add_id_dst" target="dst_inline">
                            {% trans "Create mockup organization" %}
                        </a>
                    </div>
                </div>

                <div class="add-another-inline-input-list" id="dst_inline">

                </div>
            </div>

            {% if form.dst.errors %}
            <div class="errors alert alert-danger">{{ form.dst.errors }}</div>
            {% endif %}


        </div>
    </div>

    <div class="controls form-group">
        <label for="id_title" class="col-sm-3 control-label">{% trans "Title" %} *</label>
        <div class="col-sm-7">
            <input id="id_title" name="title" type="text" class="form-control" placeholder="CEO, Lead Developer, etc." value="{{ form.title.value|default_if_none:"" }}" required>
            {% if form.username.errors %}
            <div class="errors alert alert-danger">{{ form.title.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_description" class="col-sm-3 control-label">{% trans "Description" %}</label>
        <div class="col-sm-7">
            {{ form.description }}
            {% if form.description.errors %}
            <div class="errors alert alert-danger">{{ form.description.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_start_date" class="col-sm-3 control-label">{% trans "Start Date" %} *</label>
        <div class="col-sm-7">
            <div class="data-field-wrapper">
                {{ form.start_date }}
            </div>
            {% if form.start_date.errors %}
            <div class="errors alert alert-danger">{{ form.start_date.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_end_date" class="col-sm-3 control-label">{% trans "End Date" %}</label>
        <div class="col-sm-7">
            <div class="data-field-wrapper">
                {{ form.end_date }}
            </div>
            {% if form.end_date.errors %}
            <div class="errors alert alert-danger">{{ form.end_date.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <div class="col-sm-offset-3 col-sm-7 form-action">
            <button class="btn btn-primary btn-orange{% if form.is_new %} btn-submit{% endif %}" type="submit">{% if form.is_new %}{% trans "Create new" %}{% else %}{% trans "Save changes" %}{% endif %}</button>
            {% if not request_popup %}
            <a href="{% if form.is_new %}{% url 'home' %}{% else %}.{% endif %}" class="btn btn-default btn-cancel">{% trans "Cancel" %}</a>
            {%  endif %}
            {% if request_popup %}
            <a onclick="parent.dismissAddAnotherPopup({name: '{{ request.GET.winName }}'})" class="btn btn-default btn-cancel">{% trans "Cancel" %}</a>
            {%  endif %}
        </div>


    </div>

</form>
{% endblock %}